"""Initial migration

Revision ID: 018edb03fb84
Revises: 
Create Date: 2024-06-17 19:00:18.549112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018edb03fb84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
